workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          # Supprime le cache pour éviter l'erreur de module non trouvé
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
      - name: Generate Native Android Folder
        script: |
          rm -rf android
          CI=1 npx expo prebuild --platform android
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
