workflows:
  android-workflow:
    name: U-Auben Tracker Build - Debug Mode
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @expo/vector-icons expo-router expo-asset expo-file-system expo-sharing
      
      - name: Verify Assets & Screens
        script: |
          echo "--- Nettoyage préventif ---"
          rm -rf android
          rm -rf node_modules/.cache
          mkdir -p assets/pdf
          
      - name: Lint & Type Check
        script: |
          # Vérification du code TypeScript
          npx tsc --noEmit

      - name: Generate Native Android Folder
        script: |
          # On force la régénération totale du dossier natif
          npx expo prebuild --platform android --clean

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Nettoyage profond de Gradle et compilation
          # -x lint : ignore les erreurs de style/icones
          # -x test : ignore les tests unitaires pour accélérer et éviter les plantages
          ./gradlew clean assembleRelease -x lint -x test --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
