workflows:
  android-workflow:
    name: U-Auben Tracker Android Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: openjdk17
      android:
        build_tools: 34.0.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx install-expo-modules@latest
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
