workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo Modules
        script: |
          npx install-expo-modules@latest
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
