workflows:
  android-workflow:
    name: U-Auben Tracker - Production Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
      # Correction ici : les variables personnalisées vont dans 'vars'
      vars:
        GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m"
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npx expo install --check || echo "Ignored warnings"

      - name: Verify Assets & Clean
        script: |
          echo "--- Nettoyage ---"
          rm -rf android
          rm -rf .expo
          
      - name: Generate Native Android Folder
        script: |
          npx expo prebuild --platform android --clean --no-install

      - name: Build APK Release
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease -x lint -x test --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
