workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    instance_type: mac_mini_m2 # Plus stable pour les builds hybrides
    environment:
      node: 18.19.0
      java: 17 # Utilise '17' au lieu de 'openjdk17' sur Codemagic
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx install-expo-modules@latest
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
