workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Generate Native Android Folder
        script: |
          # On s'assure que le dossier android est bien supprimé avant de le recréer
          rm -rf android
          CI=1 npx expo prebuild --platform android
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Nettoyage profond avant compilation
          ./gradlew clean
          # Compilation de l'APK sans cache pour éviter les erreurs de ressources (LinkApplicationAndroidResources)
          ./gradlew assembleRelease --no-daemon --no-build-cache --stacktrace
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
