workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Generate Native Android Folder
        script: |
          # Suppression radicale pour éviter les conflits AAPT2
          rm -rf android
          CI=1 npx expo prebuild --platform android --clear
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          # Utilisation de --info pour voir le détail de l'erreur AAPT2
          ./gradlew assembleRelease --no-daemon --no-build-cache --info --stacktrace
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
