workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: openjdk17
      android:
        build_tools: 34.0.0
        ndk: 25.2.9519653
        components:
          - platform-tools
          - build-tools-34.0.0
          - android-34
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
          cd ..
      - name: Bundle React Native assets
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..
    artifacts:
      - android/app/build/outputs/**/*.apk
