workflows:
  android-workflow:
    name: U-Auben Tracker - Production Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
      groups:
        - keystore_credentials 
    scripts:
      - name: Install dependencies
        script: |
          # Installation des dépendances avec le package.json mis à jour
          npm install --legacy-peer-deps
          
          # Force la suite même si Expo trouve des incohérences mineures
          npx expo install --check || echo "Avertissements Expo ignorés"

      - name: Verify Assets & Clean
        script: |
          echo "--- Nettoyage ---"
          rm -rf android
          mkdir -p assets/images
          
      - name: Generate Native Android Folder
        script: |
          # Génération du dossier natif sans réinstaller les modules
          npx expo prebuild --platform android --clean --no-install

      - name: Build APK Release
        script: |
          cd android
          chmod +x gradlew
          # Construction de l'APK
          ./gradlew assembleRelease -x lint -x test --stacktrace --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
