workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 20.11.0  # Mise à jour de la version Node
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Generate Native Android Folder
        script: |
          # Installation forcée d'expo si manquant et génération du dossier
          npx expo prebuild --platform android --non-interactive
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
