workflows:
  android-workflow:
    name: U-Auben Tracker Build - Debug Mode
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @expo/vector-icons expo-router expo-asset expo-file-system expo-sharing
      
      - name: Verify Assets & Screens (Le débusqueur)
        script: |
          echo "--- Vérification des fichiers critiques ---"
          ls app/room-info.tsx || echo "ERREUR: room-info.tsx introuvable"
          ls app/room-contents.tsx || echo "ERREUR: room-contents.tsx introuvable"
          echo "--- Vérification des PDF ---"
          mkdir -p assets/pdf
          ls assets/pdf/ || echo "ERREUR: Le dossier assets/pdf est vide"
          
      - name: Lint & Type Check
        script: |
          # Maintenant que nous avons tout nettoyé, tsc devrait passer au vert !
          npx tsc --noEmit

      - name: Generate Native Android Folder
        script: |
          # Correction ici : suppression de --no-interactive (inutile et obsolète)
          npx expo prebuild --platform android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Suppression de --no-daemon pour éviter certains conflits de mémoire sur Codemagic
          ./gradlew assembleRelease --stacktrace --info

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
