workflows:
  android-workflow:
    name: U-Auben Tracker - Production Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
      groups:
        - keystore_credentials 
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npx expo install --check || echo "Avertissements Expo ignorés"

      - name: Verify Assets & Clean
        script: |
          echo "--- Nettoyage ---"
          rm -rf android
          mkdir -p assets/images
          
      - name: Generate Native Android Folder
        script: |
          npx expo prebuild --platform android --clean --no-install

      - name: Build APK Release
        script: |
          cd android
          chmod +x gradlew
          # Ajout de --info pour voir l'erreur réelle en cas d'échec
          ./gradlew assembleRelease -x lint -x test --stacktrace --no-daemon --info

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
