workflows:
  android-workflow: # Nom aligné avec votre manifest.json
    name: U-Auben Tracker Android Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: openjdk17
      android:
        build_tools: 34.0.0
        ndk: 25.2.9519653
    
    scripts:
      - name: Install dependencies
        script: |
          npm install
          # Installation des modules Expo nécessaires (pour expo-sqlite utilisé dans App.js)
          npx install-expo-modules@latest

      - name: Clean Android build
        script: |
          # Utilisation du script défini dans votre package.json
          npm run clean

      - name: Bundle React Native assets
        script: |
          # Création du répertoire d'assets si manquant
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build APK (Release)
        script: |
          cd android
          # Génération de l'APK de production
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
