workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          # Installation forcée des dépendances de base
          npm install --legacy-peer-deps
          # On s'assure que les icônes et expo-router sont présents
          npm install @expo/vector-icons expo-router
      - name: Generate Native Android Folder
        script: |
          # Prebuild génère le dossier /android nécessaire au build
          npx expo prebuild --platform android
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
