workflows:
  android-workflow:
    name: U-Auben Tracker Build - Debug Mode
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @expo/vector-icons expo-router expo-asset expo-file-system expo-sharing
      
      - name: Verify Assets & Screens
        script: |
          echo "--- Nettoyage des anciens builds ---"
          rm -rf android
          echo "--- Vérification des fichiers ---"
          mkdir -p assets/pdf
          
      - name: Lint & Type Check
        script: |
          npx tsc --noEmit

      - name: Generate Native Android Folder
        script: |
          # Le flag --clean force Expo à recréer un dossier Android tout neuf
          npx expo prebuild --platform android --clean

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # 1. Nettoyage du cache Gradle
          ./gradlew clean
          # 2. Build en ignorant les erreurs de Lint (souvent la cause du crash final)
          ./gradlew assembleRelease -x lint --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
