workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: 17
    scripts:
      - name: Fix and Install dependencies
        script: |
          # Supprime le mauvais package s'il existe dans le package.json
          sed -i '' 's/"metrobundle"/"metro-runtime"/g' package.json || true
          
          # Installation propre
          npm install --legacy-peer-deps
      - name: Prebuild Expo (Si nécessaire)
        script: |
          # Cette étape génère le dossier /android s'il est manquant ou incomplet
          npx expo prebuild --platform android
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
