workflows:
  android-workflow:
    name: U-Auben Tracker Build - Debug Mode
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @expo/vector-icons expo-router expo-asset expo-file-system expo-sharing
      
      - name: Verify Assets & Screens
        script: |
          echo "--- Nettoyage total ---"
          rm -rf android
          mkdir -p assets/pdf
          
      - name: Lint & Type Check
        script: |
          # On ignore les erreurs de type ici pour ne pas bloquer le build natif
          npx tsc --noEmit || echo "Warnings TS ignorés"

      - name: Generate Native Android Folder
        script: |
          # Régénération propre
          npx expo prebuild --platform android --clean

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          # Nettoyage Gradle
          ./gradlew clean
          # On utilise assembleDebug au lieu de assembleRelease
          # C'est la méthode la plus fiable pour sortir un APK quand le mode release bloque
          ./gradlew assembleDebug -x lint -x test --stacktrace

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
