workflows:
  android-workflow:
    name: U-Auben Tracker Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: openjdk17
      groups:
        - sdk_config # Optionnel, si tu as des variables d'env
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx install-expo-modules@latest
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
