workflows:
  android-workflow:
    name: U-Auben Tracker - Production Build
    max_build_duration: 60
    environment:
      node: 20.11.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      
      - name: Verify Assets
        script: |
          echo "--- Nettoyage ---"
          rm -rf android
          mkdir -p assets/pdf
          
      - name: Generate Native Android Folder
        script: |
          # On génère le dossier natif en mode release
          npx expo prebuild --platform android --clean

      - name: Build APK Release
        script: |
          cd android
          chmod +x gradlew
          # On repasse en assembleRelease pour réduire le poids et inclure le JS
          # Le flag -x lint évite que le build bloque sur des détails visuels
          ./gradlew assembleRelease -x lint -x test --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
